<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jbschafer
 * Date: Mon, 09 Mar 2015 14:13:22 -0500
 */

$conf['title'] = 'Cedar Valley';
$conf['template'] = '20cones';
$conf['tagline'] = '<font size="2">Because every student should have the opportunity to learn how to code</font>';
$conf['license'] = 'cc-by-sa';
$conf['dmode'] = 0775;
$conf['fmode'] = 0775;
$conf['breadcrumbs'] = 0;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['moderncontact']['default'] = 'cvia.coderdojo@gmail.com';
$conf['plugin']['moderncontact']['captcha'] = 1;
$conf['plugin']['moderncontact']['recaptchakey'] = '6LdNEgMTAAAAAERxBHp9byA4VGZygA_0thiJ8rS9';
$conf['plugin']['moderncontact']['recaptchasecret'] = '6LdNEgMTAAAAAHZpWPP5JhG3e3IQudbaR5fVF7Fb';
$conf['plugin']['moderncontact']['recaptchalayout'] = 'clean';

// end auto-generated content
